version: "3.7"

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - umbrel_main_network
    volumes:
      - ./data:/app/data
    tty: true

networks:
  umbrel_main_network:
    external: true

